MVP. Included keepalive and Reconnect for Client.

diff --git a/tunnel b/tunnel
--- a/tunnel
+++ b/tunnel
@@ -40,21 +40,21 @@ duplex(){
   # Brief: Create duplex (bi-directional) connection to given channels
   # Usage: duplex <read channel> <write channel>
   local rchan="${1}" wchan="${2}"
-  socat STDIO "EXEC:curl -sfN https\://ppng.io/${rchan}!!EXEC:curl -sfNT- -o /dev/null https\://ppng.io/${wchan}"
+  socat STDIO "EXEC:curl -sfSN https\://ppng.io/${rchan}!!EXEC:curl -sfSNT- -o /dev/null https\://ppng.io/${wchan}"
 }; export -f duplex
 
 pub(){
   # Brief: Publish given string to given channel
   # Usage: pub <channel> <string>
   local chan="${1}" msg="${2}"
-  curl -sfNd "${msg}" "https://ppng.io/${chan}"
+  curl -m 3 -sfSNd "${msg}" "https://ppng.io/${chan}"
 }>/dev/null; export -f pub
 
 sub(){
   # Brief: Read from given channel
   # Usage: sub <channel>
   local chan="${1}"
-  curl -sfN "https://ppng.io/${chan}"
+  curl -sfSN "https://ppng.io/${chan}"
 }; export -f sub
 
 client(){
@@ -62,11 +62,25 @@ client(){
   # Usage: client <local_port> <peer_ID:peer_port>
   if [[ -n "${2}" ]]; then local self="$(genID):${1}" peer="${2}"; else echo "tunnel-err: Missing peer"; return 1;fi
   local peer_addr="$(digest "${peer}")"
-  local -i dial_count=0; echo "tunnel-client: Dialing..."
-  until pub "${peer_addr}" "${self}"; do echo "$(tput cuu1)tunnel-client: Dialing...${dial_count}"; ((dial_count++));done
-  echo "$(tput cuu1; tput ed)tunnel-client: Forwarding localhost:${self##*:} to ${peer}..."
-  socat "TCP4-LISTEN:${self##*:},reuseaddr,fork" EXEC:"${script_file} -c _forward ${self//:/\\:} ${peer//:/\\:}"
+  local -i dial_count=0; echo -en "tunnel-client: Dialing...\r"
+  until pub "${peer_addr}" "${self}" 2>/dev/null; do echo -en "tunnel-client: Dialing...${dial_count}\r"; ((dial_count++));done
+  echo -e "tunnel-client: Forwarding localhost:${self##*:} to ${peer}...\n"
+#  trap "echo received INT ; exec ${script_file} -a '${TUNNEL_KEY}' -c client ${self##*:} ${peer}" INT
+#  trap "echo received SIGINT ; client ${@}" INT
+  socat "TCP4-LISTEN:${self##*:},reuseaddr,fork" EXEC:"${script_file} -c _forward ${self//:/\\:} ${peer//:/\\:}" &
+  local socat_pid="${!}"
+  _keepalive 2 "$$" "$(digest "${self}" "${peer}")" &
+  wait "${!}" && kill -9 "${socat_pid}" && client "${@}"
 }>&2; export -f client
+
+_keepalive(){
+  # Brief: Ping given pairing at given intervals. Send SIGUSR to given PID (of client) on failure.
+  # Usage: _keepalive <seconds> <PID> <pairing>
+  local time="${1}" pid="${2}" pairing="${3}"
+  while sleep "${time}" && kill -0 "${pid}"; do
+    flock -nE0 /tmp/${pairing} ${script_file} -c pub "${pairing}" "ping" || return 0
+  done
+}; export -f _keepalive
 
 server(){
   # Brief: Listen to incoming connections and forward to local port
@@ -75,7 +89,7 @@ server(){
   local self_addr="$(digest "${self}")" peer
   local loop=true; trap "loop=false; pkill -s $$" INT TERM QUIT HUP
   echo "tunnel-server: PID=${BASHPID}; Started: $(date)"
-  echo "tunnel-server: Listening for incoming connections to localhost:${self##*:}..."
+  echo -e "tunnel-server: Listening for incoming connections to localhost:${self##*:}...\n"
   local -i req_count=0
   while "${loop}"; do
     peer="$(sub "${self_addr}")" || continue
@@ -91,11 +105,11 @@ _forward(){
   local self="${1}" peer="${2}"
   local source="${SOCAT_PEERADDR}:${SOCAT_PEERPORT}"
   local pairing="$(digest "${self}" "${peer}")"
-  pub "${pairing}" "${source}" || return 1
+  flock -w 1 /tmp/${pairing} ${script_file} -c pub "${pairing}" "${source}" || return "${?}"
   echo -e "tunnel-connect: ${source} <--> ${self} <--> ${peer}\n" >&2
   local wchan="$(digest "${source}" "${self}" "${peer}")" # Out Stream: Source -> Self -> Peer
   local rchan="$(digest "${peer}" "${self}" "${source}")" # In Stream: Peer -> Self -> Source
-  duplex "${rchan}" "${wchan}" || return 2
+  duplex "${rchan}" "${wchan}"
 }; export -f _forward
 
 _forwardee(){
@@ -106,7 +120,8 @@ _forwardee(){
   local loop=true; trap "loop=false; pkill -s $$" INT TERM QUIT HUP
   local source
   while "${loop}";do
-    source="$(sub "${pairing}")" || continue
+    source="$(sub "${pairing}")" || return "${?}"
+    [[ "${source}" != "ping" ]] || continue
     local rchan="$(digest "${source}" "${peer}" "${self}")" # In Stream: Source -> Peer -> Self
     local wchan="$(digest "${self}" "${peer}" "${source}")" # Out Stream: Self -> Peer-> Source
     socat "EXEC:${script_file} -c duplex ${rchan} ${wchan}" "TCP:localhost:${self##*:}" &
